[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.1.0"
aoc-runner-derive = { path = "../aoc-runner-derive" }
fnv = "1.0.6"