[package]
name = "advent-of-code-2018"
version = "0.2.0"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]

[dependencies]
aoc-runner = "0.2.0"
aoc-runner-derive = "0.2.0"
fnv = "1.0.6"
chrono = "0.4.6"