[package]
name = "advent-of-code-2018"
version = "0.2.0-alpha1"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]

[dependencies]
aoc-runner = "0.2.0-alpha1"
aoc-runner-derive = "0.2.0-alpha1"
fnv = "1.0.6"